config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'static#home'
  get '/auth/facebook/callback' => 'sessions#create' #correct session naming convention to pluralize
  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  #resources :sessions do
    #collection do
      #get :signin
      #post :signin
      #delete :logout
    #end
  #end

  resources :users do
    collection do
      get :swoliest
    end
  end

  resources :exercises
  resources :workouts do
    resources :workout_exercises, only: [:show, :index, :edit, :new, :delete]
  end

  resources :muscle_groups, only: [:index] do
    resources :exercises, only: [:show, :index, :new]
  end

  resources :workout_exercises
end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :user
  has_many :workout_exercises
  has_many :exercises, through: :workout_exercises
  has_many :comments
  has_many :users, through: :comments
  has_many :categories, through: :exercises
  accepts_nested_attributes_for :workout_exercises, allow_destroy: true
  validates :name, presence: true

  def workout_user
    User.find_by(id: self.user_id).name
  end

  def self.alpha_order
    order(name: :asc)
  end

  def workout_categories
    categories = []
    self.exercises.each do |e|
      categories << e.category.name
    end
    categories.uniq
  end

  def stub_workout_exercises
    3.times{self.workout_exercises.build}
  end

  def workout_muscle_groups
    muscle_groups = []
    self.exercises.each do |e|
      muscle_groups << e.muscle_group
    end
    muscle_groups.uniq
  end

  def titleize_name
    self.name = self.name.titleize
  end

  def distinct_exercises
    distinct_exercises = []
    self.exercises.each do |e|
      distinct_exercises << e
    end
    distinct_exercises.uniq
  end

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :require_login

  def index
    @workouts = Workout.all.alpha_order
  end

  def new
    @workout = Workout.new
    @workout.stub_workout_exercises
    @we = @workout.workout_exercises.build
  end

  def create
    @workout = Workout.create(workout_params)
    @workout.user_id = current_user.id
    @workout.titleize_name
    @workout.save
    @workout_exercises = params[:workout][:workout_exercises_attributes].values.each do |we|
        @we = WorkoutExercise.create(exercise_id: we["exercise_id"], workout_id: @workout.id, reps: we["reps"], sets: we["sets"])
          if !@we.save
            @workout.delete
            @workout.stub_workout_exercises
            render new_workout_path and return
          else
            redirect_to @workout and return
          end
        end
    end

  def show
    @workout = Workout.find_by(id: params[:id])
  end

  def edit
    @workout = Workout.find_by(id: params[:id])
    if current_user.id != @workout.user_id
      flash[:message] = "You can only edit workouts you've created"
      redirect_to workouts_path
    end
  end

  def update
    @workout = Workout.find_by(id: params[:id])
    if @workout.update(workout_params)
      flash[:message] = "Workout exercise successfully updated"
      redirect_to workout_path(@workout)
    else
      flash[:message] = @workout.errors.full_messages
    end
  end

  def destroy
    @workout = Workout.find(params[:id])
    if current_user.id !=@workout.user_id
      flash[:message] = "You can only delete workouts you've created"
      redirect_to @workout
    else
      @workout.destroy
      flash[:message] = "Workout deleted successfully"
      redirect_to workouts_path
    end
  end

  private

  def workout_params
    params.require(:workout).permit(:name, :user_id, workout_exercises_attributes: [:id, :_destroy, :reps, :sets, :exercise_id])
  end

end

app/views/workouts/edit.html.erb
<h1> Edit <%=@workout.name%> Workout </h1>

<%= form_for @workout do |f| %>

Edit Workout Name: <%= f.text_field :name %>
<br>
<h4> Edit the Exercises in this Workout? </h4>
  <%=f.fields_for :workout_exercises do |we| %>
    <li>
    Change Exercise: <%= we.collection_select(:exercise_id, Exercise.all, :id, :name)%>
    Edit Rep Count: <%= we.number_field :reps, min: 1, max:100%>
    Edit Set Count: <%= we.number_field :sets, min: 1, max:100%>
    <%=link_to "Delete this Workout Exercise?", workout_exercise_path(we.object.id), method: :delete, :confirm => "You Sure?" %>
    <% end %>
  </li>
  <br>
<%=f.submit "Update Workout" %>
<% end %>

<h4>Or add more Exercises to this Workout</h4>
<%=link_to "Create a New Workout Exercise", new_workout_workout_exercise_path(@workout.id)%>

app/views/workouts/index.html.erb
<h1> Workouts </h1>
<% if flash[:message].present? %>
<%=flash[:message] %> <br> <br>
<%end%>
<ul>
<% @workouts.each do |w| %>
  <li><%=link_to "#{w.name} - created by #{w.workout_user}", workout_path(w)%></li>
<% end %>
</ul>

<%=link_to "Create a New Workout?", new_workout_path%>

app/views/workouts/new.html.erb
<h1> Create a Workout </h1>
<%= render partial: 'layouts/errors', locals: {object: @workout} %>
<%= render partial: 'layouts/errors', locals: {object: @we} %>

<%= form_for @workout, controller: 'workouts', action: 'create' do |f| %>
Name: <%=f.text_field :name, required: true %> <br>
Workout Exercises:
<ol>
<%=f.fields_for :workout_exercises do |we| %>
  <li><%= we.collection_select(:exercise_id, Exercise.all, :id, :name,{include_blank: 'Select an Exercise to add to Your Workout'}, required: true)%>
  Rep Count: <%= we.number_field :reps, min: 1, max:100, required: true %>
  Set Count: <%= we.number_field :sets, min: 1, max:100, required: true%>
</li>
  <br>
<% end %>
</ol>
<%= f.submit "Create Workout" %>
<%end%>

app/views/workouts/show.html.erb
<h1><%= @workout.name%></h1>

<h4>Workout Exercises</h4>
<ol>
  <% @workout.workout_exercises.each do |we| %>
    <li> Name:  <%= we.exercise.name %>
      <ul>
         <li>Reps:<%= we.reps %></li>
          <li>Sets: <%= we.sets %> </li>
          </ul>
        <% end %>
      </li>
</ol>

<h4> Workout Categories </h4>
<%@workout.workout_categories.each do |category|%>
  <li><%=category%> </li>
<%end%>

<br>
<h4> Muscle Groups Hit </h4>
<% @workout.workout_muscle_groups.each do |group| %>
  <li><%=link_to "#{group.name}", muscle_group_exercises_path(group.id)%></li>
<%end%>
<br>
<h4> Exercises </h4>
<% @workout.distinct_exercises.each do |group| %>
  <li><%=link_to "#{group.name}", exercise_path(group.id)%></li>
<%end%>

<br>
<% if current_user.id == @workout.user_id %>
  <%=link_to "Edit #{@workout.name}?", edit_workout_path(@workout)%>
<% end %>
<br>

<% if current_user.id == @workout.user_id %>
<%= link_to "Delete #{@workout.name}?", workout_path, method: :delete %>
<% end %>