config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'static#home'
  get '/auth/facebook/callback' => 'sessions#create' #correct session naming convention to pluralize
  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  #resources :sessions do
    #collection do
      #get :signin
      #post :signin
      #delete :logout
    #end
  #end

  resources :users do
    collection do
      get :swoliest
    end
  end

  resources :exercises
  resources :workouts do
    resources :workout_exercises, only: [:show, :index, :edit, :new, :delete]
  end

  resources :muscle_groups, only: [:index] do
    resources :exercises, only: [:show, :index, :new]
  end

  resources :workout_exercises
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :workouts
  has_many :exercises

  validates :email, uniqueness: true, presence: true
  validates :name, presence: true
  validates :password, presence: true


  scope :swoliest, -> {User.left_joins(:workouts).group(:id).order('COUNT(workouts.id)DESC').first}

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    if !current_user
      @user = User.new
    else
      flash[:message] = "You're already signed in!"
      redirect_to current_user
    end
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :new
    end
  end


  def edit
  end

  def swoliest
    @user = User.swoliest
  end

  def show
    if !current_user
      redirect_to controller: 'users', action: 'new' #if user is not logged in, redirect to sign up
    else
      @user = User.find_by(id: params[:id])
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

app/views/users/new.html.erb
<h1> Sign Up! </h1>
<%= render partial: 'layouts/errors', locals: {object: @user} %>

<%= form_for @user, url: signup_path, method: :post do |f| %>

Name <%= f.text_field :name %> <br>
Email <%= f.text_field :email %> <br>
Password <%= f.password_field :password %><br><br>

<%= f.submit "Sign Up" %>
<%end%>

<% if @user.errors[:email].first == "has already been taken"%>
<p> You already have an account</p>
<%= link_to(controller: 'session', action: 'new', method: "new"){'Log In'}%>
<% end%>

app/views/users/show.html.erb
<h1> Welcome <%=@user.name%>! </h1>
<div>
  <% if flash[:message].present? %>
    <%= flash[:message] %>
    <% end %>
  </div>

<div>
<% if current_user.exercises.count == 0 %>
  <p> It looks like you haven't created any exercises yet. <%=link_to "Why don't you create one?", new_exercise_path%></p>
  <% else %>
  <h4>Your Exercises</h4>
  <% Exercise.all.alpha_order.each do |e| %>
      <% if e.user_id == current_user.id %>
        <li><%=link_to "#{e.name}", exercise_path(e) %></li>
        <%end%>
      <% end %> <br>

      <%=link_to "Create Another Exercise?", new_exercise_path%>
<% end %>
</div>
<div>
<% if current_user.workouts.count == 0 %> <!-- %=create class method to simplify workout.count logic % -->
  <p> You haven't created any workouts yet. <%=link_to "Create one here", new_workout_path%> </p>
<% else %>
  <h4> Your Workouts </h4>
  <% Workout.all.alpha_order.each do |w| %>
    <% if w.user_id == current_user.id %>
      <li><%=link_to "#{w.name}", workout_path(w)%></li>
      <%end%>
    <%end%>
    <br>
    <%=link_to "Create Another Workout?", new_workout_path%>
  <%end%>
</div>

app/views/users/swoliest.html.erb
<% if @user == current_user %>
    <h1>You Are the Swoliest!</h1>
    <p>The All-Spotter is Pleased</p>
    <img src="https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/b1/b17c4fc1f051ebc1ea1f9461aeccb1fbc4fe80ce_full.jpg">
    <h4>You have created <%=@user.workouts.count%> workouts! </h4>
  <%else %>
    <h1><%=@user.name%> is Swolier than Thou! </h1>
    <h4> They have created <%=@user.workouts.count%> workouts! </h4>
    <p> You have created <%=current_user.workouts.count%> workouts. </p>
  <%end%>