config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'static#home'
  get '/auth/facebook/callback' => 'sessions#create' #correct session naming convention to pluralize
  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  #resources :sessions do
    #collection do
      #get :signin
      #post :signin
      #delete :logout
    #end
  #end

  resources :users do
    collection do
      get :swoliest
    end
  end

  resources :exercises
  resources :workouts do
    resources :workout_exercises, only: [:show, :index, :edit, :new, :delete]
  end

  resources :muscle_groups, only: [:index] do
    resources :exercises, only: [:show, :index, :new]
  end

  resources :workout_exercises
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved: </h2>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
    <li> <%= msg %> </li>
    <%end %>
  </ul>
</div>
<% end %>

app/views/layouts/_loggedin_links.html.erb
<%= link_to "Home", root_path %> |
<%= link_to "Your Profile", user_path(current_user)%> |
<%= link_to "Workouts", workouts_path %> |
<%= link_to "Exercises", exercises_path %> |
<%= link_to "Muscle Groups", muscle_groups_path %> |
<%= link_to "Who is Swoliest?", swoliest_users_path %> |
<%= link_to "Log Out", logout_path, method: :delete %> |

app/views/layouts/_loggedout_links.html.erb
<%= link_to "Home", root_path %> |
<%= link_to "Sign Up", signup_path %> |
<%= link_to "Log In", signin_path %> | 
<%= link_to "Sign in with Facebook", "/auth/facebook"%>

app/views/layouts/_new_exercise.html.erb
<%=form_for @exercise, controller: 'exercises', action: 'create' do |f| %>
Name: <%=f.text_field :name %> <br>
Category:
  <%= f.collection_select(:category_id, Category.all, :id, :name, {include_blank: 'Select a Category'})%>
<br>

MuscleGroup:
  <%= f.collection_select(:muscle_group_id, MuscleGroup.all, :id, :name, {include_blank: 'Select a MuscleGroup'}) %>
  <%= f.submit "Create Exercise" %>
  <% end%>

app/views/layouts/_new_muscle_group_exercise.html.erb
<%=form_for @exercise, controller: 'exercises', action: 'create' do |f| %>
Name: <%=f.text_field :name %> <br>
Category:
  <%= f.collection_select(:category_id, Category.all, :id, :name, {include_blank: 'Select a Category'})%>
<br>


MuscleGroup:
  <%=@muscle_group.name%>
  <%= f.hidden_field :muscle_group_id %>
  <br>
<%= f.submit "Create Exercise" %>
  <% end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlatironRailsFinalProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div><%= render_nav_bar %></div>

  <body>

    <div>
        <% if flash[:message].present? %>
          <% if flash[:message].is_a?(Array) %>
            <% flash[:message].each do |f| %>
              <p style="color:red"><%= f %> </p>
          <% end %>
        <% else %>
          <p style="color:red"> <%= flash[:message] %> </p>
          <% end %>
        <% end %>
      </div>

    <%= yield %>
  </body>
</html>